#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

logpath="$basedir/logging/alarm.log"
tmpconfigpath=$basedir/logrotate.config
cat $basedir/logrotate.template.config | sed s#LOGPATH_TO_BE_REPLACED#$logpath# > $tmpconfigpath 
logrotate -v $tmpconfigpath -s $basedir/logrotate_api_daemon.status

# rm -f $tmpconfigpath
